export default {
  pollJSON: './static/leadermeter-polling-data.json',
  mapJSON: './static/canada.json',
  mapDataJSON: './static/poll_data_processed.json',
  provinceWiseDataJSON: './static/province_poll_data.json',
  tweetsJSON: './static/tweets.json',
  newsJSON: './static/newsArticles.json',
  cadidateTweetsJSON: './static/candidateTweets.json',
  mapTweetsMentionsJSON: './static/tweets_map_mentions.json',
  mapTweetsSentimentJSON: './static/tweets_map_sentiment.json',
  wordCloudTweetsJSON: './static/wordCloudData.json',
  wordCloudHashtagsTweetsJSON: './static/wordCloudHashtagsData.json',
  tweetsSentimentDistributionJSON: './static/tweets_sentiment_distribution.json',
  tweetsNumberDistributionJSON: './static/tweets_number_distribution.json',
  newsCandidateJSON: './static/candidateNews.json',
  newsBiasPieJSON: './static/biasPieChart.json',
  newsPerCandidateJSON: './static/newsBarPerCandidate.json',
  newsPerCandidateStackedJSON: './static/biasStackedBarChart.json',
  newsWordCloud: './static/newsWordCloud.json',
};